### ISSUE TITLE
Item duplication when NEI shift-clicking with Modular Storage

### ISSUE THREAD

**Issue by thor12022** [TeamCoS/Modular-Systems#107]
Items on hotbar appear to duplicate if the Modular Storage setup has no Crafting Expansion.

This is with Modular Systems 2.2.1 for Minecraft 1.7.10

Example of this can be seen here:
https://youtu.be/1WXRz_oIHq8?t=13m32s

**Comment by pauljoda** [comment]
Thanks. That video really helped me to figure out what is going on. As soon as I have some time to mess around with it I'll look into it.
