### ISSUE TITLE
Not playing well with NEI

### ISSUE THREAD

**Issue by Divineaspect** [TeamCoS/Modular-Systems#108]
http://pastebin.com/91y0EQMt

I have fastcraft installed

**Comment by Dyonovan** [comment]
Can you rename the crusherRecipes.json in config/ModularSystems/Registries and re run minecraft and see if that fixes it.

If it does, can you pastebin the renamed one so I can see what was causing the issue.

**Comment by Divineaspect** [comment]
in config/Modular-Systems/Registries?

**Comment by Dyonovan** [comment]
yes

**Comment by Divineaspect** [comment]
doing so now, is having the config/ModularSystems folder and it's contents fine?

**Comment by Dyonovan** [comment]
yes. The issue seems to be with the crusher recipes, and that json is what is used to create them. 
Could be a bad recipe in the json that is causing it

**Comment by Divineaspect** [comment]
Probably, given that I generated it with all the mods (pretty much) and now I'm down to very few.

**Comment by Dyonovan** [comment]
a yes that would do it. whenever you remove mods, its a good idea to regenerate that file

**Comment by Divineaspect** [comment]
seems to work, now to pass it along to 4 other players and a server.
Thank you for the rapid response.

**Comment by Dyonovan** [comment]
Anytime :)

Any other issues let us know

**Comment by Divineaspect** [comment]
Would fixing it on the server prevent the client crash, the reverse is not true.

**Comment by Dyonovan** [comment]
Yes. The server will send the recipe file to the client each time it logs in
So just replace on server should fix clients who connect to that server
