### ISSUE TITLE
Mod not useable in offline mode

### ISSUE THREAD

**Issue by Sir-Will** [TeamCoS/Modular-Systems#110]
playing offline crashes the client:
https://gist.github.com/TengriTorok/edcc569d87873424f726

**Comment by Dyonovan** [comment]
Yea this is my bad. Ill try and remember to fix it today if not this week for sure

**Comment by PsionicArchon** [comment]
This is a pretty bad bug, it's crashing one of my servers that's not offline. As a temporary fix I was forced to remove write permissions for the config file. Windows users can just set the file to read only.

**Comment by Sir-Will** [comment]
Why got this closed and locked?

**Comment by pauljoda** [comment]
We no longer support the 1.7.10 version. We are moving forward with 1.9

**Comment by Sir-Will** [comment]
Wow...

**Comment by pauljoda** [comment]
I'm sorry if this is upsetting, but the 1.7.10 version has not been worked on in quite some time. To manage two completely different versions would split our focus and we want to provide a new and polished version for 1.9. We have always been interested in keeping up with the latest version so supporting a version that is almost 2 years old and 2 versions behind is not in our interest. There are may great mods in 1.7.10 that can do exactly what we do and better so hopefully you can find something there.

If however you are looking to work with 1.9, we would be more than happy to do all we can
