### ISSUE TITLE
Can't crush iron or gold

### ISSUE THREAD

**Issue by kitsu** [TeamCoS/Modular-Systems#111]
It seems like something broke in 1.7.10-2.2.1 (I tried 1.7.10-2.2.0 but it crashed immediately) with the code that automatically registers recipes for any ore dusts. Most importantly the built-in iron/gold dust recipes don't exist.

The code in looks reasonable in https://github.com/TeamCoS/Modular-Systems/blob/master/src/main/java/com/pauljoda/modularsystems/core/registries/CrusherRecipeRegistry.java#L71
But I don't see any ore in the generated json.

As a work-around I'm using the following sections in crusherRecipes.json:

    {
        "input": "oreCopper",
        "output": "aobd:dustCopper:0",
        "qty": 2
    },
    {
        "input": "oreLead",
        "output": "aobd:dustLead:0",
        "qty": 2
    },
    {
        "input": "oreTin",
        "output": "aobd:dustTin:0",
        "qty": 2
    },
    {
        "input": "oreIron",
        "output": "aobd:crushedIron:0",
        "qty": 2
    },
    {
        "input": "oreGold",
        "output": "aobd:crushedGold:0",
        "qty": 2
    },

BTW what are the names for MS dusts?

**Comment by DisKorrupt** [comment]
Might i suggest telling the game to try to do "minecraft:iron_ore:0" or something like that, see if that fixes it, as many mods have their own diamond, quartz, or other similar material, but not many have replicated gold or iron
