### ISSUE TITLE
Crashed minecraft 1.7.10 without Internet - Modular Systems 2.2.1

### ISSUE THREAD

**Issue by Nib-RA** [TeamCoS/Modular-Systems#112]
First, I wish them congratulations for this mod which is wonderful for my concept; I wanted to present is an error or a crash occurs in minecraft 1.7.10 with its latest version of Modular Systems, what happens is that I wanted to start my minecraft pirate without internet because to be honest, I have no money to hire a service Internet and I do not have to buy the original version of minecraft; continuing, when I have the opportunity to connect to the Internet, there is no problem with the mod but what happens, as I said up there, but wanted to play offline and got an error on this; first thought it was just edit the file conf mod but did not work as the main configuration file, I had no content. I want corrected this error because not all people possess own Internet and want to play offline, here are the crash, I let this mod and mod NEI to review what happened.
Thanks and I hope to soon upgrade.
PS: I installed the version of your mod, 1.7.3 and that runs successfully both online or offline; second, I translated this suggestion because I not know much English and I apologize if something is mistranslated.
By the way, I'm using version forge, 10.13.4.1614 and also try it with the recommended minecraft forge for version 1.7.10, this version is 10.13.4.1558 and does not work!

[crash-2016-01-26_23.06.27-client.txt](https://github.com/TeamCoS/Modular-Systems/files/107552/crash-2016-01-26_23.06.27-client.txt)

**Comment by Divineaspect** [comment]
Having the same crash.
