### ISSUE TITLE
Generators only able to output half the reported Rf/Tick.

### ISSUE THREAD

**Issue by Xyrys** [TeamCoS/Modular-Systems#113]
Hi, 

Playing the Galactic Science pack..  Love your mod.. Using it heavily in my base.

However, I have noticed that the generators are only able to output (no matter how many connectors you have) up to half the total listed RF / tick.

Easily reproducible.  Just build a 3x3 diamond block generator with core, fuel and 4 outputs.  You get at most 1200 rf/tick from the structure.

I went as far as building a nice combo 9x9 generator that produces 38k rf / tick.  with 38 connectors it was outputing at most 19k rf/tick.  There would be 19 doing 1k/tick each and the rest 0/tick.  

Just letting you know :-)

Xyrys.

**Comment by HugoPoi** [comment]
I encountered the same issue with version 2.2.1, generator can output only the half indicated in right panel.
