### ISSUE TITLE
[1.9] 3.0.0B34 Texture issue w/ JEI and Optifine

### ISSUE THREAD

**Issue by KennyBurch** [TeamCoS/Modular-Systems#115]
Problem:

1) With JEI loaded, the following blocks appear to be mis-textured.  (They seem to actually use the music disc texture on the sides, each one a different color disc.)
* Simple Storage Expansion
* Capacity Storage Expansion
* Search Storage Expansion
* Crafting storage expansion

2) The same blocks when loaded with Optifine show to be nearly solid grey and crashes when one of the fore mentioned blocks are placed in the world. I know most mod devs don't support fixing issues for optifine problems...but I expect once #1 is fixed, the optifine crash will be avoided.

![error](https://cloud.githubusercontent.com/assets/13078744/14194318/1c277f10-f762-11e5-83a7-06c6286ada8c.jpg)

Running a SMP with the following setup:
* Forge 1816
*JEI 3.1.2.172
*Optifine 1.9.0 HD U B1
*sphax resource pack

Can give list of all other mods if needed.

**Comment by pauljoda** [comment]
Sometimes when you reload the resource pack this happens. Try restarting with sphax already enabled, should help. I'll have to track that issue down. As for optifine, I do not support them. They have long gone in and messed with what forge has done and they themselves said they won't support forge
