### ISSUE TITLE
[1.9] Crash with Forge 1832/35/39

### ISSUE THREAD

**Issue by CA2020** [TeamCoS/Modular-Systems#118]
When I try to launch an instance of Minecraft 1.9 with any of those 3 versions of Forge and Bookshelf, NeoTech and Modular Systems, I get this crash.

http://pastebin.com/2uKHMUuH

Forge updates coming out everyday, many times a day, this is crazy :P I would love to get a version working on 1835, but if it's not possible dont worry, this updates are out of control, I think at this point the best would be wait till Forge makes an stable/recommended version.

Thanks a lot.

**Comment by Dyonovan** [comment]
Fixed in 3.0.2
