### ISSUE TITLE
VersionChecker broken in older versions...

### ISSUE THREAD

**Issue by Sir-Will** [TeamCoS/Modular-Systems#129]
Good job on breaking the version checker on older versions which causes the game to crash on startup..
https://raw.githubusercontent.com/TeamCoS/Modular-Systems/master/VersionControl.xml

ModularSystems-1.7.10-2.2.1

**Comment by 23Link89** [comment]
And on top of that he won't fix it. Say goodbye to all those diamond blocks you put in your machines.

**Comment by codewarrior0** [comment]
Can confirm, version checker is broken.

**Comment by codewarrior0** [comment]
As a workaround, you may edit the `config/Modular-Systems/ModularSystems.cfg` and change this line under "version checker" to have value 3:

`    I:"Notify if out of Date? (0=Always, 1=Once, 2=Never)"=3`

**Comment by 23Link89** [comment]
Replace everything in your 'ModularSystems.cfg' file with this http://pastebin.com/sTptUjty

**Comment by Dyonovan** [comment]
Sorry about this. I have fixed it
