### ISSUE TITLE
Stack Size 64

### ISSUE THREAD

**Issue by NaySay75** [TeamCoS/Modular-Systems#135]
Hello, 
i use the modpack "Life in the Woods". For some some Reasons i cant get in the Storage a higher stack size then 64 (see picture). How can this be, and is it possible that a other Mod in the Modpack set this Limit?

![2016-12-18 15_00_32-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/24635665/21293969/d4895a3a-c532-11e6-968f-1fee9cd448c1.png)

**Comment by pauljoda** [comment]
In the version of this mod you are using that was the max stack size. It was meant to be more of a expandable chest than an AE system. The 1.10 version changed to the AE style. This is behaving as expected
