### ISSUE TITLE
Major dupe bug with modular storage (1.7.10)

### ISSUE THREAD

**Issue by ghost** [TeamCoS/Modular-Systems#136]
I'm not sure if you're willing to update the older 1.7.10 version, understandable if you're not.

If you use the 'auto fill recipe items' feature of NEI (the question mark) while browsing the modular storage, everything in your hotbar is duped. This includes backpacks full of items.

You do not need to have a crafting addon attached to your modular storage bank to produce this bug. 

Thanks in advance. 

I'll probably take a look at your code with a friend of mine, see if we can figure out what's going on and drop a fix for you. I'm stuck on 1.7.10 as most of my friends do not have enough memory to run most 1.10.2 packs.

**Comment by pauljoda** [comment]
Hey man feel free to have a look. I have no intention of fixing it as it is so old but if you submit a pull request with the fixes I can merge them
