### ISSUE TITLE
Mod erroring during loading with 1.10.2

### ISSUE THREAD

**Issue by Winddbourne** [TeamCoS/Modular-Systems#137]
Every time I try to load my pack with open modular systems  installed I get an instant crash. (modularsystems-1.10.2-3.1.0.jar)

Here is the crash report:

[crash-2017-03-02_03.00.55-client.txt](https://github.com/TeamCoS/Modular-Systems/files/813095/crash-2017-03-02_03.00.55-client.txt)

**Comment by pauljoda** [comment]
This version isn't being supported anymore unfortunately. That was kinda a test version and I never got back around to it. Maybe someday in the future.
