### ISSUE TITLE
Sorting system combined items with differing NBT

### ISSUE THREAD

**Issue by wsetzer** [TeamCoS/Modular-Systems#44]
I'm currently playing the Clouds of Darkness modpack v1.1.3, containing Modular Systems v1.7.1.  I created a Storage Core, a Crafting Expansion, a Sorting Expansion and several Capacity Expansions.  I dumped a lot of my inventory into storage, did a lot of sorting, etc to test out the mod.  I noticed after a bit that every item I possessed that differed only in NBT data had combined into one stack.  For example, I had several Hardcore Quest Mode reward bags, some basic, some good, and some greater.  The sorting system had combined them all into a single "basic bag" stack.  As another example, all the written books (minecraft:written_book) had combined into one stack.

**Comment by andrewmellinger** [comment]
I think I am also seeing he the same issue with Thaumcraft essentia.  I had four different types, sorted (by item ID) and ended up with one stack of Terra.

**Comment by pauljoda** [comment]
Oops. I plan on going back and looking over this soon and I'll keep that in mind

**Comment by pauljoda** [comment]
Fixed this issue in the next update. Should be out soon. Thanks for the feedback. If this does not work come back to this issue and let me know but from my testing it works fine
