### ISSUE TITLE
so the break replace crash still exists even in the latest verson

### ISSUE THREAD

**Issue by kurokuno** [TeamCoS/Modular-Systems#46]
02:43:46 net.minecraft.util.ReportedException: Ticking block entity
02:43:46 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
02:43:46 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
02:43:46 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
02:43:46 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
02:43:46 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
02:43:46 Caused by: java.lang.ClassCastException: com.teamcos.modularsystems.storage.tiles.TileEntityStorageExpansion cannot be cast to com.teamcos.modularsystems.storage.tiles.TileEntityStorageCore
02:43:46 at com.teamcos.modularsystems.storage.tiles.TileEntityStorageExpansion.getCore(TileEntityStorageExpansion.java:49) ~[TileEntityStorageExpansion.class:?]
02:43:46 at com.teamcos.modularsystems.storage.tiles.TileEntityStorageExpansion.isConnected(TileEntityStorageExpansion.java:188) ~[TileEntityStorageExpansion.class:?]
02:43:46 at com.teamcos.modularsystems.storage.tiles.TileEntityStorageExpansion.isConnected(TileEntityStorageExpansion.java:183) ~[TileEntityStorageExpansion.class:?]
02:43:46 at com.teamcos.modularsystems.storage.tiles.TileEntityStorageExpansion.func_145845_h(TileEntityStorageExpansion.java:222) ~[TileEntityStorageExpansion.class:?]
02:43:46 at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
02:43:46 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
02:43:46 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
02:43:46 ... 4 more

**Comment by Divineaspect** [comment]
http://pastebin.com/KYqsKweL

Having the same crash.
