### ISSUE TITLE
broken blockValues.xml error

### ISSUE THREAD

**Issue by DevPlayer-** [TeamCoS/Modular-Systems#48]
Modular Systems-1.7.10-1.7.1.jar creates a blockValues.xml with an error

	<block name="minecraft:gold_block">
        <speed/>

Note there is no opening <speed> tag nor subtags.

**Comment by pauljoda** [comment]
That is strange indeed. I'll look into this

**Comment by pauljoda** [comment]
Will be fixed in the next version. Thanks for finding that
