### ISSUE TITLE
Invisible Blocks when using OptiFine

### ISSUE THREAD

**Issue by blaze2530** [TeamCoS/Modular-Systems#49]
Mods:
Modular-Systems 1.7.10 / 1.7.1
OptiFine Ultra - 1.7.10_HD_U_B4 

All Modular Systems Blocks are invisible when using the mod OptiFine Ultra but all blocks are still functional. Disabling OptiFine Ultra will allow this mod to work as expected.
Have not tested with any other Version of OptiFine.

UPDATE:
OptiFine HD - OptiFine_1.7.10_HD_B4

The Modular Systems Blocks are now visible with the HD versions of Optifine, Looks like Ultra is the problem.

**Comment by jburrows82** [comment]
This is an Optifine issue and only they can fix the problem. There are other options to using OF that won't completely screw up Minecraft.
