### ISSUE TITLE
Wierd visual bug

### ISSUE THREAD

**Issue by evenas98** [TeamCoS/Modular-Systems#51]
![2015-02-26_17 28 49](https://cloud.githubusercontent.com/assets/6554873/6396959/00d65674-bde2-11e4-9200-1db67bf75d4e.png)
![2015-02-26_17 28 51](https://cloud.githubusercontent.com/assets/6554873/6396960/0100891c-bde2-11e4-8630-56c2df23c4e8.png)
Happens randomly, and affects speed and efficiency using lapis and redstone blocks with I/O's

**Comment by jburrows82** [comment]
Are you playing a specific modpack, or to be more specific in the question could you tell us your minecraft environment? Versions for minecraft, forge, mods etc is this SSP or SMP?

You say it's random -- are there any known conditions that are consistent (furnace is in use, you have a specific buff) etc?

Does this happen in both SSP and SMP? Does it occur cross multiple worlds?

**Comment by evenas98** [comment]
my own minecraft modpack, 1.7.10 forge 1291 alot of mods, SSP
i don't know, i have automated it, so its going on off, happens to furnace and ore processing, maybe it has to do with chunk loading ( using chicken chunks loader and its covering hole base)

**Comment by evenas98** [comment]
going to check where chunk is

**Comment by evenas98** [comment]
![2015-02-26_19 20 59](https://cloud.githubusercontent.com/assets/6554873/6398544/9e735bc0-bdec-11e4-83c6-3f51363dffff.png)
you see here, green is the chunk border!

**Comment by evenas98** [comment]
the multiblock is in 2 chunks

**Comment by evenas98** [comment]
so when i go to a diffrent dimension, it unload/loads and this happens

**Comment by pauljoda** [comment]
Are you using OptiFine?

**Comment by evenas98** [comment]
nope

**Comment by evenas98** [comment]
when i break the "stone" i get the block i used to create the multiblock (lapis)

**Comment by pauljoda** [comment]
I think I see what is happening here. When I get the chance I'll look into this

**Comment by evenas98** [comment]
awesome! :)

**Comment by pauljoda** [comment]
Found the issue. Was setting the memory of the core location to nothing so of course it wouldn't remember. Simple fix that will be in the next update
