### ISSUE TITLE
[1.7.10] Divide by Zero Crash

### ISSUE THREAD

**Issue by Archmagejay** [TeamCoS/Modular-Systems#57]
Occurs when attempting to open the modular furnace's GUI. It doesn't corrupt the world as far as I can tell and can be fixed by breaking the furnace core but until then attempting to open that furnace will crash the game.

Using:
Forge 1388
Modular Systems 1.7.3

Stack trace here: ~~http://pastebin.com/1HLfAeVf~~ (Dead)

To reproduce the crash simply build a 7x7x7 hollow cube of lapis lazuli and replace 25 of the blocks with nether brick. Like this:
![2015-05-28_23 09 48](https://cloud.githubusercontent.com/assets/5729140/7861009/e6181e7a-0590-11e5-90bd-3bf7dd830ac5.png)
Finally place any amount of usable fuel and any amount of a furnace recipe compatible ingredient in its slot. Now as soon as you close the GUI and attempt to reopen it the game crashes.

**Comment by pauljoda** [comment]
I will need another pastebin before I can look at this. The one provided does not link to anything

**Comment by medsal15** [comment]
# Configuration file

##########################################################################################################
# hammer recipes
#--------------------------------------------------------------------------------------------------------#
# This section allows you to add your own recipes for the Crack Hammer (and other rock 
# crushers). Recipes are specified in semicolon (;) delimited lists of formulas in the 
# format modid:name#y->x*modid:name#y, where x is the number of items in a stack and y 
# is the metadata value. Note that both x and y are optional, so you can use the 
# formula modid:name->modid:name for most items/blocks. 
# 
# All properties in this section will be parsed for formulas, regardless their name. 
# This lets you organize your recipe lists for easier reading.
##########################################################################################################

"hammer recipes" {
    S:custom=ministrapp:biome_stone#0->ministrapp:biome_cobble#0;ministrapp:biome_stone#1->ministrapp:biome_cobble#1;ministrapp:biome_stone#2->ministrapp:biome_cobble#2;ministrapp:biome_stone#3->ministrapp:biome_cobble#3;ministrapp:biome_stone#4->ministrapp:biome_cobble#4;ministrapp:biome_stone#5->ministrapp:biome_cobble#5;ministrapp:biome_stone#6->ministrapp:biome_cobble#6;ministrapp:biome_stone#7->ministrapp:biome_cobble#7;ministrapp:biome_stone#8->ministrapp:biome_cobble#8;ministrapp:copper_ore->2*ministrapp:chunks#5;ministrapp:biome_copper->2*ministrapp:chunks#5;ministrapp:tin_ore->2*ministrapp:chunks#6;ministrapp:biome_tin->2*ministrapp:chunks#6;ministrapp:meurodite_ore->2*ministrapp:meurodite_gem;ministrapp:biome_meurodite->2*ministrapp:meurodite_gem;ministrapp:torite_ore->2*ministrapp:chunks#9;ministrapp:biome_torite->2*ministrapp:chunks#9;ministrapp:biome_redstone->4*minecraft:redstone;ministrapp:sunstone_ore->2*ministrapp:sunstone_shard;ministrapp:biome_sunstone->2*ministrapp:sunstone_shard;ministrapp:plutonium_ore->2*ministrapp:plutonium;ministrapp:biome_plutonium->2*ministrapp:plutonium;ministrapp:uranium_ore->2*ministrapp:uranium;ministrapp:biome_uranium->2*ministrapp:uranium;ministrapp:radiant_ore->2*ministrapp:radiant_quartz;ministrapp:biome_radiant->2*ministrapp:radiant_quartz;ministrapp:titanium_ore->2*ministrapp:chunks#10;ministrapp:biome_titanium->2*ministrapp:chunks#10;ministrapp:blazium_ore->2*ministrapp:blaze_shard;ministrapp:soul_ore->2*ministrapp:soul_gem;ministrapp:copper_block->9*ministrapp:chunks#5;ministrapp:tin_block->9*ministrapp:chunks#6;ministrapp:torite_block->9*ministrapp:chunks#9;ministrapp:titanium_block->9*ministrapp:chunks#10;ministrapp:desert_quartz->2*ministrapp:desert_quartz_item;ministrapp:desert_quartz_block->4*ministrapp:desert_quartz_item;ministrapp:radiant_quartz_block->4*ministrapp:radiant_quartz;minecraft:wheat->2*ministrapp:dough;ministrapp:copper_ingot->ministrapp:chunks#5;ministrapp:tin_ingot->ministrapp:chunks#6;ministrapp:torite_ingot->ministrapp:chunks#9;ministrapp:titanium_ingot->ministrapp:chunks#10;
}


options {
    # If true, then ore generation will be handled exclusively by oregen .json files 
    # (vanilla ore generation will be disabled) [default: false]
    B:disable_standard_ore_generation=false

    # If true, then the crack hammer cannot crush ingots into powders if that 
    # crackhammer is not hard enough to crush the ingot's ore. [default: true]
    B:enforce_hardness=true

    # If true, then the crack hammer can crush ingots/ores that a pickaxe of the same 
    # material can harvest. If false, then your crack hammer must be made of a harder 
    # material than the ore you are crushing. [default: true]
    B:strong_hammers=true

    # Controls the rarity of metal ingots being found in treasure chests relative to 
    # the frequency of other chest loot items. Set to 0 to disable metal ingots from 
    # appearing in treasure chests. [range: 0.0 ~ 1000.0, default: 0.5]
    S:treasure_chest_loot_factor=0.5
}

**Comment by Archmagejay** [comment]
Here's a live link: http://pastebin.com/vF3USSgX

**Comment by luca020400** [comment]
Same problem here
log: http://pastebin.com/LsBb2zN1

**Comment by pauljoda** [comment]
This will be fixed in the new Rewrite, thank you for reporting

**Comment by luca020400** [comment]
Great
Thanks you :)

Il giorno sab 4 lug 2015 23:41 Paul Davis <notifications@github.com> ha
scritto:
