### ISSUE TITLE
Crashing right-clicking modular ore processor Core in an incomplete Cuboid  

### ISSUE THREAD

**Issue by StupidGenius** [TeamCoS/Modular-Systems#59]
Modular Systems v. 1.7.3
Mod pack: https://github.com/AIE-Guild/AIE-Nomads-Modpack

Crashing when right clicking Modular Ore Processing Core, with incomplete [Cuboid](https://github.com/TeamCoS/Modular-Systems/wiki/Cuboid)

    Stacktrace:
	    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:571)
 
    -- Item being rendered --
    Details:
	    Item Type: null
	    Item Aux: ~~ERROR~~ NullPointerException: null
	    Item NBT: null
    	    Item Foil: ~~ERROR~~ NullPointerException: null
    Stacktrace:
	    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:571)

https://gist.github.com/StupidGenius/a0f17672924597b7418a
Example Image: http://i.imgur.com/WLz2Taj.jpg

Other mods in picture:
Mekanism's Universal Cables
Thermal Expansion's Creative Energy Cell
Iron Chest's Obsidian Chest

**Comment by pauljoda** [comment]
Will be fixed in the rewrite
