### ISSUE TITLE
Modular Furnace Addition doesn't work

### ISSUE THREAD

**Issue by Selim042** [TeamCoS/Modular-Systems#62]
I have 8 Modular Furnace Additions on my 5x5x5 furnace, and they are not increasing how many things are smelted per operation.

**Comment by pauljoda** [comment]
This is well fixed in the new version

**Comment by Selim042** [comment]
I have the latest version, 1.7.3.

**Comment by pauljoda** [comment]
I'm aware the current released version has that issue,  however since your version the mod has been completely redone and will be released soon. That version of the mod is no longer in development so the bug will persist until the new one is released. Please be patient

**Comment by Selim042** [comment]
I thought you meant it as, "yea, that bug was in 1.7.2, so upgrade to 1.7.3" to fix it.
