### ISSUE TITLE
Issues with the Modular Furnace

### ISSUE THREAD

**Issue by RaiderofRamen** [TeamCoS/Modular-Systems#65]
Alright, so this is going to be a long one. I've found quite a few bugs in both the modular furnace's compatibility with other mods, but also in its functionality.

1. The furnace increases in both speed and efficiency based on the cuboid's makeup every time you open the interface while it is running, not just on the cuboid's creation.

2. The modular furnace will not input or output until the burn time reaches zero. It almost seems to disassemble the cuboid, as the overlay disappears as well.

3. After the burn time reaches 0 and the cuboid reforms and allows access for the I/O ports, any adjacent Thermal Dynamics itemducts will remain disconnected from the port, unless they have a servo or filter forcing the connection.

4. I'm not totally sure on this one, because as I said in the previous bugs, the furnace increases in speed and efficiency every time its burning. It seems like the block configurations for the cuboids aren't working 100% correctly. For instance, in the default blockValues.json, diamond blocks are supposed to have s speed factor of -8 with a 'floor' of -40. Yet, when I built a furnace made entirely of diamond blocks (hooray for Mystcraft), I ended up with 20% speed. Perhaps I'm misinterpreting what I'm reading, but that doesn't seem like what it's supposed to be.

Thank you for taking the time to read my bug reports and crashes, and I hope to see more great work from you in the future!

**Comment by medsal15** [comment]
4. Not only on furnace but on crusher too. I made a 140% efficiency-350% speed crusher using diamond blocks.

**Comment by luca020400** [comment]
I have a random crash when I close the guy
http://pastebin.com/dScjt0xQ

**Comment by RaiderofRamen** [comment]
@luca020400 The I/O port stops when the furnace is burning. In fact, it almost seems like the entire structure disassembles when it's burning.

**Comment by pauljoda** [comment]
Fixed in next update

**Comment by luca020400** [comment]
Bug 1 by @RaiderofRamen isn't fixed
