### ISSUE TITLE
Duplicating Bone Meal

### ISSUE THREAD

**Issue by RaiderofRamen** [TeamCoS/Modular-Systems#68]
There is a recipe in the modular crusher to turn 1 piece of bone meal (or any other white dye) into six pieces of bone meal. Nice job with all the bug fixes :)

**Comment by pauljoda** [comment]
Keep them coming. Seriously you found really important bugs we somehow missed so we could get them fixed quickly. It would have taken me a while to notice those. 

I'll have Dyonovan look into this and he should have it fixed pretty quick. Good catch

**Comment by Dyonovan** [comment]
Already looking into it :)
