### ISSUE TITLE
Crashing on launch - 2.1.2

### ISSUE THREAD

**Issue by Cuppycake** [TeamCoS/Modular-Systems#73]
Updating my modpack I get a crash with 2.1.2 
Crash:http://pastebin.com/HEw3K4WS

Removing Modular Systems completely allows the pack to launch. 
I can guarantee their are not two versions of the mod in the pack.

Version 2.1 is a clean Initialization. No issues there. Only with the newest version.

**Comment by Dyonovan** [comment]
Looking into this now

**Comment by Dyonovan** [comment]
Ok I have NO clue what happened there. Seems like the original version got packaged with the new one. I have deleted the one on curse and have just uploaded a new version that is correct. It should take about 15 mins to be approved but once you can see version 2.1.2 its the correct one. Sorry about this.

**Comment by Cuppycake** [comment]
No worries at all glad I could help catch it and help save others some headaches :)
Thanks for your quick response and fix. Have a good one.
