### ISSUE TITLE
FML Confirm

### ISSUE THREAD

**Issue by Cuppycake** [TeamCoS/Modular-Systems#74]
Upon server and level start Modular Systems wants me to /fml confirm for missing blocks with the new version you just put out installed. Is this normal now or another issue?

**Comment by Dyonovan** [comment]
what blocks does it say are missing?

**Comment by Cuppycake** [comment]
Pretty much everything it looks like. Trying to launch the pack now Im getting the following crash:
http://pastebin.com/F6P4prWa

The crash is random and doesn't always happen.

**Comment by Dyonovan** [comment]
it should be safe for the blocks. back up the world and give it a shot. /fml confirm does a backup automatically too.

**Comment by Dyonovan** [comment]
Delete the registries directory in config/Modular-systems and let me know if it happens again

**Comment by Cuppycake** [comment]
Did that, it was empty. No Change.

**Comment by Dyonovan** [comment]
hmm very wierd. ok give me a min and ill look into it

**Comment by Dyonovan** [comment]
Try this version http://www.beyondrealitypack.com:8080/job/Modular%20Systems/lastSuccessfulBuild/artifact/build/libs/ModularSystems-1.7.10-2.1.3-B23.jar

if it works ill push another release. *Should fix it*

**Comment by Cuppycake** [comment]
Still asks for a confirmation on level load. Only blocks under Modular Systems are:
Solid Fuel Bank
Modular Furnace Core
RestoneFlux Power Bank (Typo in the mod? I imagine its intended to be RedstoneFlux)
Liquid Fuel Power Bank
Modular Systems I/O
IC2 LV Fuel Power Bank
Modular Generator Core

**Comment by Dyonovan** [comment]
go ahead and confirm it. worse case you can restore the backup it creates but should be ok.

**Comment by Cuppycake** [comment]
I am confirming it I am saying the only blocks in the mod are the ones above. Nothing else is in the world, creative tab, or NEI.

**Comment by Dyonovan** [comment]
ok thats good then. Thats all the blocks right now. This version is a complete re-write and thats all we have added so far :)

**Comment by Dyonovan** [comment]
And thanks for pointing out the typo. Fixing that right now

**Comment by Cuppycake** [comment]
Oh I was unaware lol. No problem
