### ISSUE TITLE
Add option to add Crusher Recipes

### ISSUE THREAD

**Issue by marco6971** [TeamCoS/Modular-Systems#76]
Is it possibile to add own recipe in modular ore processing? (I want add a recipe to crush sand into silicone from ender io)

**Comment by Dyonovan** [comment]
This has been in the back of my mind for a while. It won't be through minetweaker, but there will be a config file you can add recipes.

**Comment by Dyonovan** [comment]
After next update there will be a json file that you can add recipes to
