### ISSUE TITLE
NullPointerException from NEI when hovering sort button in Modular Storage

### ISSUE THREAD

**Issue by cesarmalari** [TeamCoS/Modular-Systems#79]
NEI exception + console spam when hovering over the sort button in Modular Storage

http://pastebin.com/iTwG7xRD

The Modular Storage in question has a number of storage blocks and a sorting upgrade, but no other upgrades.

**Comment by pauljoda** [comment]
Since it seems to not be us, I'm closing this for now. If the issue persists and can be easily brought back on us I will reopen this
