### ISSUE TITLE
Make generator multiplicity consume multiple fuel.

### ISSUE THREAD

**Issue by mille449** [TeamCoS/Modular-Systems#87]
If not enough fuel is not available, it should output a reduced value.  So if you have 4x multiplicity and 2 coal, 2 coal is consumed and you get 2x power.  If you have 4.5x multiplicity and are using coal, you could either get 4x power for 4 coal or 4.5x power and for 5 coal.  I like the first option.

**Comment by Dyonovan** [comment]
Instead it will now reduce the tick time by the multiplicity. ie If you have a multiplicity of 4x, actual burn time is now burntime / 4.
