### ISSUE TITLE
Crash When Clicking Creative Tab

### ISSUE THREAD

**Issue by CrimsonCrystal** [TeamCoS/Modular-Systems#91]
Just as the title states, Minecraft crashes whenever I select the Modular Systems tab in creative. This does not occur with any other creative tabs.
http://pastebin.com/qL71nTBv

**Comment by pauljoda** [comment]
Do you have anything disabled? Like the furnace or anything like that

**Comment by CrimsonCrystal** [comment]
No, I do not.

**Comment by Dyonovan** [comment]
Would it be possible for you to downgrade your forge version to the latest recommended (1448) to see if its a forge issue or not?

**Comment by CrimsonCrystal** [comment]
Okay, I'll try to downgrade forge, as well as download the new version that came out three hours ago
(Bookshelf 1.20 and Modular Systems 2.2.0)

**Comment by CrimsonCrystal** [comment]
Using the recommended version of forge and the bare minimums required to run Modular Systems (Modular Systems, Bookshelf, CodeChickenCore, and NEI), upon trying to open creative tab I get this crash: http://pastebin.com/BQZs2mjB

**Comment by Dyonovan** [comment]
Ok. Found the reason for the crash. Give me a few mins and I will publish a new version as there are a couple of issues we just fixed

**Comment by Dyonovan** [comment]
Fixed in 2.2.1. Just waiting for curse to approve then it will be available
