### ISSUE TITLE
Generator "First Initialization" Bug

### ISSUE THREAD

**Issue by BillboardEric** [TeamCoS/Modular-Systems#93]
I'll let the video do the explaining
https://www.youtube.com/watch?v=KwULJsNjgzw&feature=youtu.be
(Basically the generation tab doesn't update until the second opening)

**Comment by Dyonovan** [comment]
Its been fixed by not opening the gui the first time you go to open the generator when you are forming it.

**Comment by BillboardEric** [comment]
I am running the latest version of the library and the mod :/

**Comment by Dyonovan** [comment]
Just to double check. 2.2.0 was released about 30 mins ago. You updated to that?

**Comment by BillboardEric** [comment]
Yep, was patiently waiting for it :P

**Comment by Dyonovan** [comment]
kk let me check it out

**Comment by Dyonovan** [comment]
Ok found the issue and its bigger then just the generator. Working on a fix as we speak

**Comment by BillboardEric** [comment]
Alright, cool

**Comment by Dyonovan** [comment]
Ok found the issue and its fixed. Will be publishing a new version of M-S in a few mins as I am also going to fix another issue at the same time.

**Comment by Dyonovan** [comment]
Fixed in 2.2.1. Just waiting for curse to approve then it will be available
