### ISSUE TITLE
Different "shift key" definitions are used

### ISSUE THREAD

**Issue by goalie1248** [TeamCoS/Modular-Systems#95]
Some occasions require pressing the actual shift key on the keyboard (like expanding the WAILA stats when looking at the furnace generator). Others require the actual crouch key as set in the keybinds (accessing the solid fuel power banks inventory).

**Comment by Dyonovan** [comment]
Opps. Wrong issue # Reopened

**Comment by goalie1248** [comment]
Damn it Dyo I WILL NOT BE SILENCED

**Comment by goalie1248** [comment]
WHAT DID I SAY ABOVE PAUL

**Comment by pauljoda** [comment]
Its not valid anymore. We have moved to 1.9
