### ISSUE TITLE
Problem With Configuring Block Values

### ISSUE THREAD

**Issue by RaiderofRamen** [TeamCoS/Modular-Systems#98]
I'm currently playing with Modular Systems in a modpack, and I tried to add Enderium blocks from Thermal expansion through the /configureBlockValues gui. However, when I try to make a cuboid with the blocks using any of the cores, it doesn't form.

**Comment by pauljoda** [comment]
It is possible that that particular block has a tile entity or other property that I'm picking up on. Things like tile entities and a few other things are blocked to keep from crashing with odd blocks. I'm not sure how Thermal Expansion creates that block, but it seems that they are doing something differently. 

I don't want to sound insulting, but are you sure it is formed correctly? If you remove those blocks for say cobblestone will it work? I want to make sure that the issue has to do with the block itself and not the formation. I'll try messing around with it myself if I find the time and see if I can pick out what TE is doing.

**Comment by RaiderofRamen** [comment]
Yes, I tried removing all of the enderium blocks and replacing them with other types, and they all worked just fine. I even tried only using one single enderium block in the structure and it didn't work.

Sorry, I wish I could be of more help in discovering exactly what the problem is.

**Comment by Dyonovan** [comment]
Fixed
